version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0 # Specify your .NET runtime version
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y nginx

  pre_build:
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore

  build:
    commands:
      - echo "Building the project..."
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo "Publishing the project..."
      - dotnet publish -c Release -o ./publish
      - echo "Deploying to NGINX..."
      - cp -r ./publish/* /var/www/html/
      - sudo systemctl restart nginx
      - echo "Application deployed successfully!"

artifacts:
  files:
    - /var/www/html/*
