version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET SDK
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel LTS
      - export PATH=$PATH:$HOME/.dotnet

  pre_build:
    commands:
      - echo Restoring NuGet packages
      - dotnet restore --verbosity detailed  # Increased verbosity

  build:
    commands:
      - echo Building the application
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Running tests
      - dotnet test

artifacts:
  files:
    - '**/*'
