version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
      - dotnet --version # Verify the .NET version
  pre_build:
    commands:
      - echo Restoring NuGet packages...
      - dotnet restore
  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release
      - echo Publishing the project...
      - dotnet publish --configuration Release --output ./saeedawsapps/web
  post_build:
    commands:
      - echo Running tests...
      - dotnet test --configuration Release
      - echo Build and test completed on `date`
artifacts:
  files:
    - saeedawsapps/web/**/*  # All files under the web folder
    - appspec.yml            # Include the appspec.yml file
  discard-paths: no          # Retain directory structure
