version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y nginx

  build:
    commands:
      - echo "Build started on: $(date)"
      - sudo cp Index.cshtml /Views/Home/

  post_build:
    commands:
      - sudo systemctl restart nginx
      - echo "NGINX is running with the copied Index.cshtml"

artifacts:
  files:
    - Views/Home/Index.cshtml
