version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
      - dotnet --version # Verify the .NET version
  pre_build:
    commands:
      - echo Restoring NuGet packages...
      - dotnet restore
  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Running tests...
      - dotnet test --configuration Release
      - echo Build and test completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: bin/Release/net8.0/publish
